# Generated by Django 5.0.7 on 2024-08-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queryresponse",
            name="type",
            field=models.CharField(
                choices=[("text", "TEXT"), ("table", "TABLE"), ("chart", "CHART")],
                max_length=100,
            ),
        ),
    ]
