# Generated by Django 5.0.7 on 2024-08-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_alter_queryresponse_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queryresponse",
            name="response",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
